### ISSUE TITLE
Ocean Parameterizations

### ISSUE THREAD

**Issue by cmbengue** [CliMA/OceanParameterizations.jl#65]
# The Climate Modeling Alliance
### Purpose

To guide the development of all sub-grid scale parameterizations of the ocean model.

#### Requirements

- [ ] The code solution is modular
- [ ] Representation of the main ocean processes (details to follow) are included

#### Quality Criteria

- [ ] Demonstrates low (to be quantified later) mix-layer depth biases in the Tropics
- [ ] Demonstrates low (to be quantified later) mix-layer depth biases in the Southern Ocean

#### Approach

We will research, design, and implement novel boundary layer and mesoscale parameterizations.

### Cost/Benefits/Risks

TBD

### Personnel and Resources

TBD

### Composition of the Solution

Source code
- Boundary layer parameterization module
- Mesoscale parameterization module
Test modules
API documentation

### Inputs

TBD

### Key Results and Deliverables

- [ ] CATKE journal article published
- [ ] Run set of channel/Neverworld library of solutions

### Task Breakdown And Tentative Due Date

```[tasklist]
### Boundary layer parameterization [03/23]
- [ ] Calibrate boundary layer parameterization
- [ ] Write CATKE paper
- [ ] Write Discovery Loop paper
```

```[tasklist]
### Mesoscale parameterization [04/23]
- [ ] Formulate vertical structure based on scaling theory
```

***
- Approved by: Raf
- Approval date:

### CC
@rafferarri @cmbengue
